# Site settings
title: duse - preview
url: https://www.duse.io
description: "Distributed Secrets"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: duse.io
  social: GitHub
  credits: Credits

social:
  github: http://github.com/duse-io

# Credits content
credits: 'This site is based on a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
